---
# Collectd-Daemon fuer Gateway Server

- name: install collectd
  apt: pkg=collectd state=installed 
  notify:
    - restart collectd 

- name: enable collectd
  service: name=collectd enabled=yes    
  notify:
    - restart collectd 

- name: create config directory
  file: path=/etc/collectd state=directory
  notify:
    - restart collectd

- name: deploy collectd.conf 
  template: src=collectd.conf.j2 dest=/etc/collectd/collectd.conf 
  notify:
    - restart collectd

- name: deploy collection.conf
  template: src=collection.conf.j2 dest=/etc/collectd/collection.conf
  notify:
    - restart collectd

- name: deploy filters.conf
  template: src=filters.conf.j2 dest=/etc/collectd/filters.conf
  notify:
    - restart collectd

- name: deploy thresholds.conf
  template: src=thresholds.conf.j2 dest=/etc/collectd/thresholds.conf
  notify:
    - restart collectd

- name: create plugins directory
  file: path=/opt/collectd-python state=directory
  notify:
    - restart collectd

- name: remove collectd_fastd.py
  file: path=/opt/collectd-python/collectd_fastd.py state=absent
  notify:
    - restart collectd

- name: deploy fastd.py
  template: src=fastd.py.j2 dest=/opt/collectd-python/fastd.py
  notify:
    - restart collectd
  when: collectd.collect_fastd

- name: deploy dhcp.py
  template: src=dhcp.py.j2 dest=/opt/collectd-python/dhcp.py
  notify:
    - restart collectd
  when: collectd.collect_dhcp

- name: deploy ipv4ipv6.py
  template: src=ipv4ipv6.py.j2 dest=/opt/collectd-python/ipv4ipv6.py
  notify:
    - restart collectd



