- name: install required packages for grafana
  apt:
    pkg: "{{ item }}"
    update_cache: yes
    cache_valid_time: 900
    state: installed
  with_items:
    - apt-transport-https
    - sqlite3
 
- name: add repo key for grafana (packagecloud.io)
  apt_key:
    id: 'D59097AB'
    url: 'https://packagecloud.io/gpg.key'
    state: present

- name: add repo for grafana
  apt_repository:
    repo: 'deb https://packagecloud.io/grafana/stable/debian/ jessie main' #Use this line even if you are on Ubuntu or another Debian version. 
    state: present

- name: install grafana
  apt:
    pkg: "grafana"
    update_cache: yes
    cache_valid_time: 900
    state: installed

- name: deploy initial grafana.db
  copy:
    src: grafana.db
    dest: /var/lib/grafana/grafana.db
    force: false
  notify:
    - restart grafana-server

- name: modify graphite datasource in grafana.db
  shell: sqlite3 /var/lib/grafana/grafana.db "update data_source set url = 'https://{{graphite.nginx.host_name}}' where id=2;"

- name: Ensure grafana.db are owned by grafana
  file:
    path: /var/lib/grafana/grafana.db
    owner: grafana
    group: grafana

- name: deploy grafana.ini
  template:
    src: grafana.ini.j2
    dest: /etc/grafana/grafana.ini
  notify:
    - restart grafana-server

- name: Start and enable grafana
  service:
    name: grafana-server
    state: started
    enabled: yes
