---

- name: Enable nf_conntrack module
  modprobe: name=nf_conntrack state=present

- name: Enable nf_conntrack on system startup
  lineinfile: dest=/etc/modules line="nf_conntrack"

- name: Set nf_conntrack_max to a higher value
  sysctl: name="net.netfilter.nf_conntrack_max" value=524288 sysctl_set=yes state=present reload=yes

- name: Set nf_conntrack_tcp_timeout_established to 86400 (one day)
  sysctl: name="net.netfilter.nf_conntrack_tcp_timeout_established" value=86400 sysctl_set=yes state=present reload=yes

- name: Set nf_conntrack_tcp_timeout_time_wait to 60
  sysctl: name="net.netfilter.nf_conntrack_tcp_timeout_time_wait" value=60 sysctl_set=yes state=present reload=yes

- name: Get current nf_conntrack hashsize
  shell: "cat /sys/module/nf_conntrack/parameters/hashsize"
  register: nf_conntrack_hashsize
  changed_when: false
  always_run: yes

- name: Set nf_conntrack hashsize to a higher value
  shell: "echo 32768 > /sys/module/nf_conntrack/parameters/hashsize"
  when: "nf_conntrack_hashsize.stdout != '32768'"