
- name: ben√∂tigte Pakete installieren
  apt:
    pkg: "{{ item }}"
    state: installed
  with_items:
    - build-essential
    - checkinstall
    - pkg-config
    - libnl-3-dev
    - libcap-dev
    - libgps-dev

- name: batctl-Quellen laden und entpacken
  unarchive: src=batctl-2015.1.tar.gz dest=/usr/src

- stat: path=/usr/local/sbin/batctl
  register: batctl

- name: batctl bauen
  shell: "make && checkinstall -y make install"
  args:
    chdir: /usr/src/batctl-2015.1
  when: batctl.stat.exists == False

- name: alfred-Quellen laden und entpacken
  unarchive: src=alfred-2015.1.tar.gz dest=/usr/src

- stat: path=/usr/local/sbin/alfred
  register: alfred

- name: alfred bauen
  shell: "make && checkinstall -y make install"
  args:
    chdir: /usr/src/alfred-2015.1
  notify:
   - restart networking
  when: alfred.stat.exists == False
    
# creating batman interfaces
- name: Create interfaces - batman file
  template: src="batman.j2" dest="/etc/network/interfaces.d/30_batman.cfg"
  notify:
    - restart networking

#append line in interfaces file for reading additional config files
- name: let read interfaces from interfaces
  lineinfile: dest="/etc/network/interfaces" line="source /etc/network/interfaces.d/*"
  notify:
    - restart networking
