---
- name: restart fastd
  service: name=fastd state=restarted
  when: not (ansible_distribution == "Debian" and ansible_distribution_major_version == "10")

- name: restart fastd@vpn
  systemd:
    name: fastd@vpn
    state: reloaded
  when: ansible_distribution == "Debian" and ansible_distribution_major_version == "10"
