---
# Tasks for network interfaces

# adding ffrl natv4 address to loopback adapter
- name: Create interfaces - add ffrl to loopback
  lineinfile: 
     dest='/etc/network/interfaces'
     regexp='^[ \t]+up ip address add.*$'
     insertafter='^iface lo inet loopback.*$'
     line='        up ip address add {{server_ipv4_nat}} dev lo'
  notify:
    - restart networking

# creating gretap tunnels to ffrl
- name: Create interfaces - gretap to ffrl
  template: src="gre_ffrl.j2" dest="/etc/network/interfaces.d/40_gre_ffrl.cfg"
  notify:
    - restart networking

#append line in interfaces file for reading additional config files
- name: let read interfaces from interfaces
  lineinfile: dest="/etc/network/interfaces" line="source /etc/network/interfaces.d/*"
  notify:
    - restart networking