---
- name: Install NRPE-Server
  package:
    name: nagios-nrpe-server
    state: latest

- name: Configure NRPE-Server
  template: "src=nrpe_local.cfg.j2 dest='/etc/nagios/nrpe_local.cfg' owner=root group=root"
  notify: Reload nagios-nrpe-server

- name: Install Nagios Plugins
  package:
    name: nagios-plugins-standard
    state: latest

- name: Install bc
  package:
    name: bc
    state: latest

- name: Install vnstat
  package:
    name: vnstat
    state: latest

- name: Install vnstati
  package:
    name: vnstati
    state: latest

- name: Install sudo
  apt:
    name: sudo
    state: present

- name: Install RAM check
  copy: "src=check_ram dest='/usr/lib/nagios/plugins/check_ram' owner=root group=root mode=a+x"

- name: Install bandwith check
  copy: "src=check_bandwidth dest='/usr/lib/nagios/plugins/check_bandwidth' owner=root group=root mode=a+x"

- name: Install check_eth
  copy: "src=check_eth dest='/usr/lib/nagios/plugins/check_eth' owner=root group=root mode=a+x"

- name: Install check_systemd_service
  copy: "src=check_systemd_service dest='/usr/lib/nagios/plugins/check_systemd_service' owner=root group=root mode=a+x"

- name: Install check_fastd
  copy: "src=check_fastd dest='/usr/lib/nagios/plugins/check_fastd' owner=root group=root mode=a+x"

- name: Install check_tunneldigger
  copy: "src=check_tunneldigger dest='/usr/lib/nagios/plugins/check_tunneldigger' owner=root group=root mode=a+x"

- name: Install Speedtest
  package:
    name: speedtest-cli
    state: latest

- name: Install check_speedtest-cli plugin
  copy: src=check_speedtest-cli.sh dest=/usr/lib/nagios/plugins/check_speedtest-cli.sh owner=root group=root mode=a+x

- name: Install DHCP lease check
  package:
    name: dhcpd-pools
    state: present
  when: not (ansible_distribution == 'Ubuntu' and ansible_distribution_version == '16.04')

- name: Install check_batip
  template: "src=check_batip.j2 dest='/usr/lib/nagios/plugins/check_batip' owner=root group=root mode=a+x"

- name: Install check_batip6
  template: "src=check_batip6.j2 dest='/usr/lib/nagios/plugins/check_batip6' owner=root group=root mode=a+x"

- name: Install check_iproute
  copy: "src=check_iproute dest='/usr/lib/nagios/plugins/check_iproute' owner=root group=root mode=a+x"

- name: Install check_iproute6
  copy: "src=check_iproute6 dest='/usr/lib/nagios/plugins/check_iproute6' owner=root group=root mode=a+x"

- name: Install check_bird_sessions
  copy: "src=check_bird_sessions dest='/usr/lib/nagios/plugins/check_bird_sessions' owner=root group=root mode=a+x"

- name: Install check_bird6_sessions
  copy: "src=check_bird6_sessions dest='/usr/lib/nagios/plugins/check_bird6_sessions' owner=root group=root mode=a+x"

- name: Install check_borg
  copy: "src=check_borg dest='/usr/lib/nagios/plugins/check_borg' owner=root group=root mode=a+x"

- name: Install sudo permissions
  template: "src=sudoers.j2 dest='/etc/sudoers.d/nrpe' owner=root group=root mode=440"

- name: enable NRPE-Server
  systemd:
    name: nagios-nrpe-server
    state: started
    enabled: yes
