---
# Fastd-Daemon fuer Gateway Server

- name: install fastd
  apt: pkg=fastd state=installed

- name: create dummy peer
  template: src=dummy.j2 dest=/etc/fastd/vpn/peers/dummy
  notify:
    - restart fastd

- name: enable fastd
  service: name=fastd state=running enabled=yes



