# Pakete installieren
- name: nginx installieren
  apt:
    pkg: "{{ item }}"
    update_cache: no
    state: installed
  with_items:
    - nginx

- stat: path=/etc/ssl/fullchain.pem
  register: sslcert

# nginx konfigurieren
- name: Konfig-Datei default-init kopieren
  copy: src=default-init dest=/etc/nginx/sites-available/default
  notify: restart nginx
  when: sslcert.stat.exists == False

- name: Konfig-Datei karte kopieren
  copy: src=karte-init dest=/etc/nginx/sites-available/karte
  notify: restart nginx
  when: sslcert.stat.exists == False

- name: Konfig-Datei karte aktivieren
  file: src=/etc/nginx/sites-available/karte dest=/etc/nginx/sites-enabled/karte state=link
  notify: restart nginx

- name: Konfig-Datei graphite kopieren
  copy: src=graphite-init dest=/etc/nginx/sites-available/graphite
  notify: restart nginx
  when: sslcert.stat.exists == False

- name: Konfig-Datei graphite aktivieren
  file: src=/etc/nginx/sites-available/graphite dest=/etc/nginx/sites-enabled/graphite state=link
  notify: restart nginx

- name: nginx restarten wenn initial
  meta: flush_handlers
  when: sslcert.stat.exists == False

- name: Letsencrypt-Zertifikat beantragen und installieren
  shell: cd /usr/src && if [ ! -e simp_le ]; then git clone https://github.com/thomastweets/simp_le ; fi && cd simp_le && ./bootstrap.sh && if [ ! -e venv/bin/python ]; then ./venv.sh; fi && export PATH=/usr/src/simp_le/venv/bin:$PATH && cd /etc/ssl && simp_le --email info@freifunk-muensterland.de -f account_key.json -f key.pem -f fullchain.pem -d service.freifunk-muensterland.de:/var/www/html -d karte.freifunk-muensterland.org:/var/www/html/maps -d karte.freifunk-muensterland.de:/var/www/html/maps -d graphite.freifunk-muensterland.de:/var/www/html
  notify: restart nginx
  when: sslcert.stat.exists == False

- name: Konfig-Datei default kopieren
  copy: src=default dest=/etc/nginx/sites-available/default
  notify: restart nginx

- name: Konfig-Datei karte kopieren
  copy: src=karte dest=/etc/nginx/sites-available/karte
  notify: restart nginx

- name: Konfig-Datei graphite kopieren
  copy: src=graphite dest=/etc/nginx/sites-available/graphite
  notify: restart nginx

- name: index.html kopieren
  copy: src=index.html dest=/var/www/html

- name: Cronjob f√ºr Zertifikatserneuerung
  cron: name="simp_le" weekday="2" hour="20" minute="0" job="cd /etc/ssl && PATH=/usr/src/simp_le/venv/bin:/usr/sbin:/usr/bin:/sbin:/bin simp_le --email info@freifunk-muensterland.de -f account_key.json -f key.pem -f fullchain.pem -d service.freifunk-muensterland.de:/var/www/html -d karte.freifunk-muensterland.org:/var/www/html/maps -d karte.freifunk-muensterland.de:/var/www/html/maps -d graphite.freifunk-muensterland.de:/var/www/html && systemctl reload nginx"

