---
- name: install figlet and lsb-release
  apt:
    pkg: [ 'figlet', 'lsb-release' ]
    state: present

- name: check figlet
  stat: 
    path: /usr/bin/figlet
  register: figlet_stat

- name: figlet name
  command: /usr/bin/figlet -c -w 50 {{ freifunk.kurzname }}
  register: figlethost
  check_mode: no
  when: figlet_stat.stat.exists
  changed_when: False

- name: Create /etc/update-motd.d/ directory if not existent
  file:
    path: /etc/update-motd.d
    state: directory

- name: Disable default motd if necessary
  file:
    path: /etc/update-motd.d/{{ item }}
    state: absent
  with_items:
    - 00-header
    - 10-help-text

- name: create motd update script
  template: 
    src: 99-custom.j2 
    dest: /etc/update-motd.d/99-custom
    mode: "u+rwx,g+rx,o+rx"
