# install bind9 service 
# ---
- name: install bind9
  apt: pkg=bind9 state=installed

- name: deploy named.conf.local
  template: src=named.conf.local.j2 dest=/etc/bind/named.conf.local
  notify:
    - restart bind9

- name: deploy named.conf.options
  template: src=named.conf.options.j2 dest=/etc/bind/named.conf.options
  notify:
    - restart bind9

- name: create named.conf.ffms
  template: src=named.conf.ffms.j2 dest=/etc/bind/named.conf.ffms
  notify:
    - restart bind9

- name: create named.conf.freifunk-muensterland
  template: src=named.conf.freifunk-muensterland.j2 dest=/etc/bind/named.conf.freifunk-muensterland
  notify:
    - restart bind9

- name: create named.conf
  template: src=named.conf.j2 dest=/etc/bind/named.conf
  notify:
    - restart bind9

- name: create db file for other ffms access
  template: src=db.other.j2 dest=/etc/bind/db.other.ffms
  notify:
    - restart bind9

- name: create own db file for each subdomaene
  template: src=db.ffms.j2 dest=/etc/bind/db.{{item}}.ffms
  notify:
    - restart bind9
  with_items: bind.ffms_for_groups

- name: create own db file for gateway servers and backbone servers
  template: src=db.servers.ffms.j2 dest=/etc/bind/db.servers.ffms
  notify:
    - restart bind9

- name: create own db file for services
  template: src=db.services.ffms.j2 dest=/etc/bind/db.services.ffms
  notify:
    - restart bind9

- name: create own db file for freifunk-muensterland.de
  template: src=db.freifunk-muensterland.de.j2 dest=/etc/bind/db.freifunk-muensterland.de
  notify:
    - restart bind9

- name: create own db file for servers.freifunk-muensterland.de
  template: src=db.servers.freifunk-muensterland.de.j2 dest=/etc/bind/db.servers.freifunk-muensterland.de
  notify:
    - restart bind9

- name: create own db file for services.freifunk-muensterland.de
  template: src=db.services.freifunk-muensterland.de.j2 dest=/etc/bind/db.services.freifunk-muensterland.de
  notify:
    - restart bind9

- name: create own db file for freifunk-muenster.de
  template: src=db.freifunk-muenster.de.j2 dest=/etc/bind/db.freifunk-muenster.de
  notify:
    - restart bind9

- name: create own db file for gw.freifunk-muenster.de
  template: src=db.gw.freifunk-muenster.de.j2 dest=/etc/bind/db.gw.freifunk-muenster.de
  notify:
    - restart bind9
