---
# Tasks for bridge interface

# do apt-get
- name: install bridge-utils
  apt: pkg=bridge-utils state=installed update_cache=yes

# creating bridge interface
- name: Create interfaces - bridge file
  template: src="bridge.j2" dest="/etc/network/interfaces.d/10_bridge.cfg"
  notify:
    - restart networking

#append line in interfaces file for reading additional config files
- name: let read interfaces from interfaces
  lineinfile: dest="/etc/network/interfaces" line="source /etc/network/interfaces.d/*.cfg"
  notify:
    - restart networking