---
- name: Install dependencies
  apt:
    pkg: ['python3-pip']
    state: present

- name: Install dependencies
  apt:
    pkg: ['python3-distutils', 'python3-setuptools', 'python3-dev']
    state: present
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '18.04'

- name: Install python dependencies
  pip: 
    name: ['psutil', 'netifaces']
    state: present
    executable: pip3

- name: create systemd files
  template: 
    src: py-respondd.service.j2
    dest: /etc/systemd/system/py-respondd.service
  notify: systemctl reload

- name: Clone py-respondd repo
  git: 
    repo: https://github.com/descilla/py-respondd.git
    dest: /opt/py-respondd/
    clone: yes
    update: yes
  notify: restart respondd

- name: create config.json files
  template: 
    src: config.json.j2
    dest: /opt/py-respondd/config.json
  notify: restart respondd

- name: enable py-respondd service
  service:
    name: py-respondd.service
    enabled: yes
