---
# Pakete installieren

- name: Abh채ngigkeiten von ffmap-backend installieren
  apt:
    pkg: "{{ item }}"
    update_cache: yes
    state: installed
  with_items:
    - python3
    - python3-networkx

- name: git f체r ffmap-backend
  git: repo=https://github.com/FreiFunkMuenster/ffmap-backend.git dest=/usr/src/ffmap-backend version=multi-domaenen-mapserver

- name: git f체r tools
  git: repo=https://github.com/FreiFunkMuenster/tools.git dest=/usr/src/tools version=master

- name: cron f체r ffmap-backend
  cron: name="ffmap-backend" minute="*/2" job="/usr/src/tools/create_map_data.sh >/dev/null 2>&1"

