---
# Pakete installieren

- name: Abh채ngigkeiten von ffmap-backend installieren
  apt:
    pkg: "{{ item }}"
    update_cache: yes
    state: installed
  with_items:
    - python3
    - python3-networkx
    - jq

- name: git f체r ffmap-backend
  git: repo=https://github.com/FreiFunkMuenster/ffmap-backend.git dest=/usr/src/ffmap-backend force=yes version=dcd6609030e32ebbf73692e78e7a2426ab1efdc4

- name: git f체r tools
  git: repo=https://github.com/FreiFunkMuenster/tools.git dest=/usr/src/tools force=yes version=c6cad7f46d44859174faf47f388ff8183ab45273

- name: create_map_data.sh kopieren
  copy: src=create_map_data.sh dest=/usr/local/bin/create_map_data.sh mode=0755

- name: cron f체r create_map_data.sh
  cron: name="ffmap-backend" minute="*" job="PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin /usr/local/bin/create_map_data.sh >/dev/null 2>&1"

